dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
packages:
  github.com/smartcontractkit/chainlink-solana/pkg/monitoring:
    interfaces:
      ChainReader:
  github.com/smartcontractkit/chainlink-solana/pkg/monitoring/metrics:
    interfaces:
      FeedBalances:
      Fees:
        config:
          filename: "Fees.go"
      NetworkFees:
      NodeBalances:
      NodeSuccess:
      ReportObservations:
      SlotHeight:
  github.com/smartcontractkit/chainlink-solana/pkg/solana/client:
    interfaces:
      ReaderWriter:
  github.com/smartcontractkit/chainlink-solana/pkg/solana/config:
    interfaces:
      Config:
        config:
          filename: config.go
          case: underscore
  github.com/smartcontractkit/chainlink-solana/pkg/solana/fees:
    interfaces:
      Estimator:
        config:
          filename: "Estimator.go"
  github.com/smartcontractkit/chainlink-solana/pkg/solana/txm:
    interfaces:
      SimpleKeystore:
        config:
          filename: simple_keystore.go
          case: underscore
      TxManager:
  github.com/smartcontractkit/chainlink-solana/pkg/solana/logpoller:
    interfaces:
      RPCClient:
      WorkerGroup:
      filtersI:
        config:
          inpackage: True
          dir: "pkg/solana/logpoller"
          filename: mock_filters.go
          mockname: mockFilters
      logsLoader:
        config:
          inpackage: True
          dir: "pkg/solana/logpoller"
          filename: mock_logs_loader.go
          mockname: mockLogsLoader
      ORM:
        config:
          inpackage: True
          dir: "pkg/solana/logpoller"
          filename: mock_orm.go
          mockname: MockORM

