[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "id.json"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"

# [programs.mainnet]
# TODO: add pubkeys

# [programs.testnet]
# TODO: add pubkeys

# [programs.devnet]
# TODO: add pubkeys

[programs.localnet]
access_controller = "9xi644bRR8birboDGdTiwBq3C7VEeR7VuamRYYXCubUW"
log-read-test = "J1zQwrBNBngz26jRPNWsUSZMHJwBwpkoDitXRV95LdK4"
ocr_2 = "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ" # need to rename the idl to satisfy anchor.js...
store = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"