name: gauntlet-release

on:
  push:
    tags:
      - "gauntlet-solana-contracts-v[0-9]+.[0-9]+.[0-9]" # i.e. gauntlet-solana-contracts-v1.0.0
      - "gauntlet-solana-contracts-v[0-9]+.[0-9]+.[0-9]+-rc*" # i.e. gauntlet-solana-contracts-v1.0.0-rc1
      - "gauntlet-serum-multisig-v[0-9]+.[0-9]+.[0-9]"
      - "gauntlet-serum-multisig-v[0-9]+.[0-9]+.[0-9]+-rc*"
      - "gauntlet-solana-v[0-9]+.[0-9]+.[0-9]"
      - "gauntlet-solana-v[0-9]+.[0-9]+.[0-9]+-rc*"

jobs:
  release-gauntlet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Set Env Variables
        run: echo "PKG_NAME=gauntlet-solana-contracts" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-solana-contracts-')
        run: echo "PKG_NAME=gauntlet-serum-multisig" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-serum-multisig-')
        run: echo "PKG_NAME=gauntlet-solana" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/gauntlet-solana-')
      - name: Build Gauntlet
        run: cd gauntlet && yarn && yarn bundle
      - name: Create Archive
        run: tar cfvz ${{env.PKG_NAME}}.tar.gz gauntlet/packages/${{env.PKG_NAME}}/**
      - name: Release Gauntlet
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.PKG_NAME}}.tar.gz
            gauntlet/bin/gauntlet-*
